spring:
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: ${db.datasource.url}
    #url: jdbc:postgresql://localhost:5432/vault-employee-pre
    username: postgres #${db.username}
    password: #${db.password}
    driver-class-name: org.postgresql.Driver
    
hello: Hello from Github and Spring Cloud Config Server (pre profile)
